/* //last code before sunday
 * GraphColoringClustering.h
 *
 *  Created on: Nov 27, 2025
 *      Author: opp_env
 */

/*
 * GraphColoringClustering.h
 */

#ifndef __CLUSTERINGMANET_GRAPHCOLORINGCLUSTERING_H_
#define __CLUSTERINGMANET_GRAPHCOLORINGCLUSTERING_H_

#include <map>
#include <set>

#include "omnetpp.h"

#include "inet/common/InitStages.h"
#include "inet/common/packet/Packet.h"
#include "inet/transportlayer/contract/udp/UdpSocket.h"
#include "inet/networklayer/common/L3AddressResolver.h"
#include "inet/networklayer/common/L3AddressTag_m.h"

class GraphColoringClustering: public omnetpp::cSimpleModule,
        public inet::UdpSocket::ICallback {
public:
    enum Role {
        UNDECIDED = 0, CLUSTER_HEAD = 1, MEMBER = 2, GATEWAY = 3
    };

protected:
    // --- node state ---
    int nodeId = -1;
    int currentColor = -1;
    int role = UNDECIDED;
    int clusterId = -1;

    // --- timing parameters ---
    omnetpp::simtime_t helloInterval;
    omnetpp::simtime_t helloJitter;
    omnetpp::simtime_t neighborTimeout;
    omnetpp::simtime_t maintenanceInterval;
    omnetpp::simtime_t coloringInterval;
    omnetpp::simtime_t dataInterval;
    omnetpp::simtime_t dataJitter;

    // --- self messages ---
    omnetpp::cMessage *helloTimer = nullptr;
    omnetpp::cMessage *colorTimer = nullptr;
    omnetpp::cMessage *maintenanceTimer = nullptr;
    omnetpp::cMessage *dataTimer = nullptr;     // Timer to trigger data sending

    // --- UDP state ---
    inet::UdpSocket socket;
    inet::L3Address destAddress;
    int localPort = -1;
    int destPort = -1;

    // --- visualization ---
    int lastDisplayColor = -1;
    int numHosts = -1; // <--- Add this variable

    // --- neighbor table ---
    struct NeighborInfo {
        int neighborId;
        inet::L3Address ipAddress; // <--- NEW: Store the real IP
        int color;
        int role;
        int clusterId;
        omnetpp::simtime_t lastHeard;
    };

    std::map<int, NeighborInfo> neighborTable;
    // --- NEW: Backbone Routing Table ---
    // Maps Final_Dest_ID -> Next_Hop_Gateway_ID
    std::map<int, int> backboneRoutingTable;

    // --- Forwarding Filter Memory ---
    std::set<std::pair<int, int>> seenDataPackets; // Stores <srcId, seqNum>
    int mySeqNum = 0;                              // Counter for my own packets

    // ------------ STATISTICAL SIGNALS ------------

    // --- PDR Counters & signals---
    long numDataSent = 0;      // Generated by me
    long numDataReceived = 0;  // Received by me (as final dest)
    omnetpp::simsignal_t pdrSentSignal;
    omnetpp::simsignal_t pdrReceivedSignal;

    // Global Counting of roles
    omnetpp::simsignal_t chChangeSignal;
    omnetpp::simsignal_t gwChangeSignal;
    omnetpp::simsignal_t memberChangeSignal;

    // Counting for one node
    omnetpp::simsignal_t roleSignal;

    // end-to-end delay
    omnetpp::simsignal_t delaySignal;

    // Records the size of received packets
    omnetpp::simsignal_t throughputSignal;

protected:
    // multi-stage initialization (INET style)
    virtual int numInitStages() const override {
        return inet::NUM_INIT_STAGES;
    }
    virtual void initialize(int stage) override;
    virtual void handleMessage(omnetpp::cMessage *msg) override;
    virtual void finish() override;

    // timer handlers
    void handleHelloTimer();
    void handleColorTimer();
    void handleMaintenanceTimer();
    void handleDataTimer();

    // UDP receive
    void handleUdpPacket(inet::Packet *pk);

    // NEW: UdpSocket callbacks
    virtual void socketDataArrived(inet::UdpSocket *socket, inet::Packet *pk)
            override;
    virtual void socketErrorArrived(inet::UdpSocket *socket,
            inet::Indication *indication) override {
    }
    virtual void socketClosed(inet::UdpSocket *socket) override {
    }

    // clustering helpers
    bool pruneNeighbors();
    void updateDisplayColor();
    void recomputeRole();
};

#endif /* __CLUSTERINGMANET_GRAPHCOLORINGCLUSTERING_H_ */
